[project]
name = "bi-ranked-choice-voting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "munpy>=0.0.0",
    "pandas>=2.2.3",
    "ruff>=0.8.3",
    "seaborn>=0.13.2",
]
